<?php

/**
 * BaseLocal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $Evento
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getTitle()  Returns the current record's "title" value
 * @method Doctrine_Collection getEvento() Returns the current record's "Evento" collection
 * @method Local               setId()     Sets the current record's "id" value
 * @method Local               setTitle()  Sets the current record's "title" value
 * @method Local               setEvento() Sets the current record's "Evento" collection
 * 
 * @package    museu
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('local');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Evento', array(
             'local' => 'id',
             'foreign' => 'local_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}