<?php

/**
 * BaseVoteEstampagem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $estampagem_id
 * @property integer $user_id
 * @property enum $vote
 * @property boolean $aproved
 * @property Estampagem $Estampagem
 * @property sfGuardUser $User
 * 
 * @method integer        getId()            Returns the current record's "id" value
 * @method integer        getEstampagemId()  Returns the current record's "estampagem_id" value
 * @method integer        getUserId()        Returns the current record's "user_id" value
 * @method enum           getVote()          Returns the current record's "vote" value
 * @method boolean        getAproved()       Returns the current record's "aproved" value
 * @method Estampagem     getEstampagem()    Returns the current record's "Estampagem" value
 * @method sfGuardUser    getUser()          Returns the current record's "User" value
 * @method VoteEstampagem setId()            Sets the current record's "id" value
 * @method VoteEstampagem setEstampagemId()  Sets the current record's "estampagem_id" value
 * @method VoteEstampagem setUserId()        Sets the current record's "user_id" value
 * @method VoteEstampagem setVote()          Sets the current record's "vote" value
 * @method VoteEstampagem setAproved()       Sets the current record's "aproved" value
 * @method VoteEstampagem setEstampagem()    Sets the current record's "Estampagem" value
 * @method VoteEstampagem setUser()          Sets the current record's "User" value
 * 
 * @package    museu
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVoteEstampagem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vote_estampagem');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('estampagem_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('vote', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 1,
              1 => 2,
              2 => 3,
              3 => 4,
              4 => 5,
             ),
             'notnull' => true,
             ));
        $this->hasColumn('aproved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estampagem', array(
             'local' => 'estampagem_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}