<?php

/**
 * BaseVoteObjecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $objecto_id
 * @property integer $user_id
 * @property enum $vote
 * @property boolean $aproved
 * @property Objecto $Objecto
 * @property sfGuardUser $User
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getObjectoId()  Returns the current record's "objecto_id" value
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method enum        getVote()       Returns the current record's "vote" value
 * @method boolean     getAproved()    Returns the current record's "aproved" value
 * @method Objecto     getObjecto()    Returns the current record's "Objecto" value
 * @method sfGuardUser getUser()       Returns the current record's "User" value
 * @method VoteObjecto setId()         Sets the current record's "id" value
 * @method VoteObjecto setObjectoId()  Sets the current record's "objecto_id" value
 * @method VoteObjecto setUserId()     Sets the current record's "user_id" value
 * @method VoteObjecto setVote()       Sets the current record's "vote" value
 * @method VoteObjecto setAproved()    Sets the current record's "aproved" value
 * @method VoteObjecto setObjecto()    Sets the current record's "Objecto" value
 * @method VoteObjecto setUser()       Sets the current record's "User" value
 * 
 * @package    museu
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVoteObjecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vote_objecto');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('objecto_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('vote', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 1,
              1 => 2,
              2 => 3,
              3 => 4,
              4 => 5,
             ),
             'notnull' => true,
             ));
        $this->hasColumn('aproved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Objecto', array(
             'local' => 'objecto_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}