<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property clob $resume
 * @property clob $overview
 * @property string $image
 * @property boolean $featured
 * @property sfGuardUser $User
 * 
 * @method integer     getId()       Returns the current record's "id" value
 * @method integer     getUserId()   Returns the current record's "user_id" value
 * @method string      getTitle()    Returns the current record's "title" value
 * @method clob        getResume()   Returns the current record's "resume" value
 * @method clob        getOverview() Returns the current record's "overview" value
 * @method string      getImage()    Returns the current record's "image" value
 * @method boolean     getFeatured() Returns the current record's "featured" value
 * @method sfGuardUser getUser()     Returns the current record's "User" value
 * @method News        setId()       Sets the current record's "id" value
 * @method News        setUserId()   Sets the current record's "user_id" value
 * @method News        setTitle()    Sets the current record's "title" value
 * @method News        setResume()   Sets the current record's "resume" value
 * @method News        setOverview() Sets the current record's "overview" value
 * @method News        setImage()    Sets the current record's "image" value
 * @method News        setFeatured() Sets the current record's "featured" value
 * @method News        setUser()     Sets the current record's "User" value
 * 
 * @package    museu
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('resume', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('overview', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('featured', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'resume',
              2 => 'overview',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}