<?php

/**
 * BaseEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property clob $overview
 * @property date $start_date
 * @property date $end_date
 * @property integer $local_id
 * @property Local $Local
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getTitle()      Returns the current record's "title" value
 * @method clob    getOverview()   Returns the current record's "overview" value
 * @method date    getStartDate()  Returns the current record's "start_date" value
 * @method date    getEndDate()    Returns the current record's "end_date" value
 * @method integer getLocalId()    Returns the current record's "local_id" value
 * @method Local   getLocal()      Returns the current record's "Local" value
 * @method Evento  setId()         Sets the current record's "id" value
 * @method Evento  setTitle()      Sets the current record's "title" value
 * @method Evento  setOverview()   Sets the current record's "overview" value
 * @method Evento  setStartDate()  Sets the current record's "start_date" value
 * @method Evento  setEndDate()    Sets the current record's "end_date" value
 * @method Evento  setLocalId()    Sets the current record's "local_id" value
 * @method Evento  setLocal()      Sets the current record's "Local" value
 * 
 * @package    museu
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evento');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('overview', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('start_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('end_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('local_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Local', array(
             'local' => 'local_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}