<?php

/**
 * BaseLocalObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $Objecto
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getTitle()   Returns the current record's "title" value
 * @method Doctrine_Collection getObjecto() Returns the current record's "Objecto" collection
 * @method LocalObject         setId()      Sets the current record's "id" value
 * @method LocalObject         setTitle()   Sets the current record's "title" value
 * @method LocalObject         setObjecto() Sets the current record's "Objecto" collection
 * 
 * @package    museu
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocalObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('local_object');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Objecto', array(
             'local' => 'id',
             'foreign' => 'local_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}