estampagem:
  class: sfDoctrineRouteCollection
  options:
    model:                Estampagem
    module:               estampagem
    prefix_path:          /estampagem
    column:               id
    with_wildcard_routes: true

vote_objecto:
  class: sfDoctrineRouteCollection
  options:
    model:                VoteObjecto
    module:               voteObj
    prefix_path:          /voteObj
    column:               id
    with_wildcard_routes: true

commentobject:
  class: sfDoctrineRouteCollection
  options:
    model:                Commentobject
    module:               comentObj
    prefix_path:          /comentObj
    column:               id
    with_wildcard_routes: true

evento:
  class: sfDoctrineRouteCollection
  options:
    model:                Evento
    module:               evento
    prefix_path:          /evento
    column:               id
    with_wildcard_routes: true

objecto:
  class: sfDoctrineRouteCollection
  options:
    model:                Objecto
    module:               objecto
    prefix_path:          /objecto
    column:               id
    with_wildcard_routes: true

produto:
  class: sfDoctrineRouteCollection
  options:
    model:                Produto
    module:               objecto
    prefix_path:          /objecto
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true
    
news:
  class: sfDoctrineRouteCollection
  options:
    model:  News
    module: news
    prefix_path:  news
    column: id
    with_wildcard_routes: true
#news:
#  class: News
#  options:
#    model:                News
#    module:               news
#    prefix_path:          /news
#    column:               id
#    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: user, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
