<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/11 14:51:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=museu',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
