<?php

/**
 * CategoriaObjectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaObjectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaObjectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoriaObjecto');
    }
}