<?php

/**
 * CommentObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CommentObject');
    }
}