<?php

/**
 * CommentEstampagemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentEstampagemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentEstampagemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CommentEstampagem');
    }
}