<?php

/**
 * EstampagemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstampagemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstampagemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estampagem');
    }
}