<?php

/**
 * IncorporacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IncorporacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IncorporacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Incorporacao');
    }
}