<?php

/**
 * LocalObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocalObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LocalObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LocalObject');
    }
}