<?php

/**
 * LocalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LocalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Local');
    }
}