<?php

/**
 * ObjectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Objecto');
    }
}