<?php

/**
 * ProdutoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProdutoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProdutoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Produto');
    }
}