<?php

/**
 * ProprietarioObjectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProprietarioObjectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProprietarioObjectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProprietarioObjecto');
    }
}