<?php

/**
 * SuperCategoriaObjectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuperCategoriaObjectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuperCategoriaObjectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SuperCategoriaObjecto');
    }
}