<?php

/**
 * TipologiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipologiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipologiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipologia');
    }
}