<?php

/**
 * VoteObjectoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VoteObjectoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VoteObjectoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VoteObjecto');
    }
}