<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addproduto extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('produto', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 100,
             ),
             'overview' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('produto');
    }
}