<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('objecto', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'overview' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'obs' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'designation' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'image' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'denomination' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'finality' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'history' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'buy_date' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'years' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'price' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             'specification' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'bibliography' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('objecto');
    }
}