<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('evento', 'evento_local_id_local_id', array(
             'name' => 'evento_local_id_local_id',
             'local' => 'local_id',
             'foreign' => 'id',
             'foreignTable' => 'local',
             ));
        $this->addIndex('evento', 'evento_local_id', array(
             'fields' => 
             array(
              0 => 'local_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('evento', 'evento_local_id_local_id');
        $this->removeIndex('evento', 'evento_local_id', array(
             'fields' => 
             array(
              0 => 'local_id',
             ),
             ));
    }
}