<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('estampagem', 'estampagem_incorporation_id_incorporacao_id', array(
             'name' => 'estampagem_incorporation_id_incorporacao_id',
             'local' => 'incorporation_id',
             'foreign' => 'id',
             'foreignTable' => 'incorporacao',
             ));
        $this->addIndex('estampagem', 'estampagem_incorporation_id', array(
             'fields' => 
             array(
              0 => 'incorporation_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('estampagem', 'estampagem_incorporation_id_incorporacao_id');
        $this->removeIndex('estampagem', 'estampagem_incorporation_id', array(
             'fields' => 
             array(
              0 => 'incorporation_id',
             ),
             ));
    }
}