<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('estampagem', 'estampagem_tipolocia_id_tipologia_id', array(
             'name' => 'estampagem_tipolocia_id_tipologia_id',
             'local' => 'tipolocia_id',
             'foreign' => 'id',
             'foreignTable' => 'tipologia',
             ));
        $this->addIndex('estampagem', 'estampagem_tipolocia_id', array(
             'fields' => 
             array(
              0 => 'tipolocia_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('estampagem', 'estampagem_tipolocia_id_tipologia_id');
        $this->removeIndex('estampagem', 'estampagem_tipolocia_id', array(
             'fields' => 
             array(
              0 => 'tipolocia_id',
             ),
             ));
    }
}