<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version45 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('objecto', 'objecto_incorporation_id_incorporacao_id', array(
             'name' => 'objecto_incorporation_id_incorporacao_id',
             'local' => 'incorporation_id',
             'foreign' => 'id',
             'foreignTable' => 'incorporacao',
             ));
        $this->addIndex('objecto', 'objecto_incorporation_id', array(
             'fields' => 
             array(
              0 => 'incorporation_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('objecto', 'objecto_incorporation_id_incorporacao_id');
        $this->removeIndex('objecto', 'objecto_incorporation_id', array(
             'fields' => 
             array(
              0 => 'incorporation_id',
             ),
             ));
    }
}