<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('estampagem', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'intentario' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'designation' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'overview' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'length' => '',
             ),
             'autor' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'price' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             'rel_date' => 
             array(
              'type' => 'string',
              'length' => '125',
             ),
             'material' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'tecnique' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'colors' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'altura' => 
             array(
              'type' => 'string',
              'length' => '125',
             ),
             'largura' => 
             array(
              'type' => 'string',
              'length' => '125',
             ),
             'imagem' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'obs' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'bibliography' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('objecto', 'local_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->dropTable('estampagem');
        $this->removeColumn('objecto', 'local_id');
    }
}