<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version44 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('objecto', 'incorporation_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('objecto', 'incorporation_id');
    }
}