<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('vote_objecto', 'vote_objecto_objecto_id_objecto_id', array(
             'name' => 'vote_objecto_objecto_id_objecto_id',
             'local' => 'objecto_id',
             'foreign' => 'id',
             'foreignTable' => 'objecto',
             ));
        $this->addIndex('vote_objecto', 'vote_objecto_objecto_id', array(
             'fields' => 
             array(
              0 => 'objecto_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('vote_objecto', 'vote_objecto_objecto_id_objecto_id');
        $this->removeIndex('vote_objecto', 'vote_objecto_objecto_id', array(
             'fields' => 
             array(
              0 => 'objecto_id',
             ),
             ));
    }
}