<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version37 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('estampagem', 'owner_id', 'integer', '4', array(
             ));
        $this->addColumn('estampagem', 'local_id', 'integer', '4', array(
             ));
        $this->addColumn('estampagem', 'tipolocia_id', 'integer', '4', array(
             ));
        $this->addColumn('estampagem', 'incorporation_id', 'integer', '4', array(
             ));
        $this->addColumn('estampagem', 'featured', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('estampagem', 'owner_id');
        $this->removeColumn('estampagem', 'local_id');
        $this->removeColumn('estampagem', 'tipolocia_id');
        $this->removeColumn('estampagem', 'incorporation_id');
        $this->removeColumn('estampagem', 'featured');
    }
}