<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('estampagem', 'estampagem_category_id_categoria_objecto_id', array(
             'name' => 'estampagem_category_id_categoria_objecto_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'categoria_objecto',
             ));
        $this->addIndex('estampagem', 'estampagem_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('estampagem', 'estampagem_category_id_categoria_objecto_id');
        $this->removeIndex('estampagem', 'estampagem_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
    }
}