<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('objecto', 'objecto_local_id_local_id', array(
             'name' => 'objecto_local_id_local_id',
             'local' => 'local_id',
             'foreign' => 'id',
             'foreignTable' => 'local',
             ));
        $this->addIndex('objecto', 'objecto_local_id', array(
             'fields' => 
             array(
              0 => 'local_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('objecto', 'objecto_local_id_local_id');
        $this->removeIndex('objecto', 'objecto_local_id', array(
             'fields' => 
             array(
              0 => 'local_id',
             ),
             ));
    }
}