<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('comment_object', 'comment_object_objecto_id_objecto_id', array(
             'name' => 'comment_object_objecto_id_objecto_id',
             'local' => 'objecto_id',
             'foreign' => 'id',
             'foreignTable' => 'objecto',
             ));
        $this->addIndex('comment_object', 'comment_object_objecto_id', array(
             'fields' => 
             array(
              0 => 'objecto_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('comment_object', 'comment_object_objecto_id_objecto_id');
        $this->removeIndex('comment_object', 'comment_object_objecto_id', array(
             'fields' => 
             array(
              0 => 'objecto_id',
             ),
             ));
    }
}