<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version38 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('estampagem', 'estampagem_owner_id_proprietario_objecto_id', array(
             'name' => 'estampagem_owner_id_proprietario_objecto_id',
             'local' => 'owner_id',
             'foreign' => 'id',
             'foreignTable' => 'proprietario_objecto',
             ));
        $this->addIndex('estampagem', 'estampagem_owner_id', array(
             'fields' => 
             array(
              0 => 'owner_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('estampagem', 'estampagem_owner_id_proprietario_objecto_id');
        $this->removeIndex('estampagem', 'estampagem_owner_id', array(
             'fields' => 
             array(
              0 => 'owner_id',
             ),
             ));
    }
}