<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/20 11:39:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=museu',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
