Produto:
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:
      type: string(100)
      notnull: true
    overview:
      type: clob
      notnull: true